
// Generated by Cadence Encounter(R) RTL Compiler RC13.10 - v13.10-s006_1

// Verification Directory fv/mpc_verilog 

module register12bit(data_in, data_out, wr_e, clr, clk);
  input [11:0] data_in;
  input wr_e, clr, clk;
  output [11:0] data_out;
  wire [11:0] data_in;
  wire wr_e, clr, clk;
  wire [11:0] data_out;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10, n_0;
  DFEC1 \data_out_reg[0] (.RN (n_0), .C (clk), .D (data_in[0]), .E
       (wr_e), .Q (data_out[0]), .QN (UNCONNECTED));
  DFEC1 \data_out_reg[10] (.RN (n_0), .C (clk), .D (data_in[10]), .E
       (wr_e), .Q (data_out[10]), .QN (UNCONNECTED0));
  DFEC1 \data_out_reg[6] (.RN (n_0), .C (clk), .D (data_in[6]), .E
       (wr_e), .Q (data_out[6]), .QN (UNCONNECTED1));
  DFEC1 \data_out_reg[7] (.RN (n_0), .C (clk), .D (data_in[7]), .E
       (wr_e), .Q (data_out[7]), .QN (UNCONNECTED2));
  DFEC1 \data_out_reg[8] (.RN (n_0), .C (clk), .D (data_in[8]), .E
       (wr_e), .Q (data_out[8]), .QN (UNCONNECTED3));
  DFEC1 \data_out_reg[9] (.RN (n_0), .C (clk), .D (data_in[9]), .E
       (wr_e), .Q (data_out[9]), .QN (UNCONNECTED4));
  DFEC1 \data_out_reg[11] (.RN (n_0), .C (clk), .D (data_in[11]), .E
       (wr_e), .Q (data_out[11]), .QN (UNCONNECTED5));
  DFEC1 \data_out_reg[1] (.RN (n_0), .C (clk), .D (data_in[1]), .E
       (wr_e), .Q (data_out[1]), .QN (UNCONNECTED6));
  DFEC1 \data_out_reg[2] (.RN (n_0), .C (clk), .D (data_in[2]), .E
       (wr_e), .Q (data_out[2]), .QN (UNCONNECTED7));
  DFEC1 \data_out_reg[3] (.RN (n_0), .C (clk), .D (data_in[3]), .E
       (wr_e), .Q (data_out[3]), .QN (UNCONNECTED8));
  DFEC1 \data_out_reg[4] (.RN (n_0), .C (clk), .D (data_in[4]), .E
       (wr_e), .Q (data_out[4]), .QN (UNCONNECTED9));
  DFEC1 \data_out_reg[5] (.RN (n_0), .C (clk), .D (data_in[5]), .E
       (wr_e), .Q (data_out[5]), .QN (UNCONNECTED10));
  INV1 g65(.A (clr), .Q (n_0));
endmodule

module mexor(in, out);
  input [4:0] in;
  output [4:0] out;
  wire [4:0] in;
  wire [4:0] out;
  wire n_1, n_2;
  assign out[0] = in[0];
  assign out[1] = in[1];
  NAND20 g162(.A (in[0]), .B (in[1]), .Q (n_1));
  INV2 g163(.A (n_1), .Q (n_2));
  XNR20 g164(.A (n_2), .B (in[4]), .Q (out[4]));
  XNR20 g165(.A (n_2), .B (in[3]), .Q (out[3]));
  XNR20 g166(.A (n_2), .B (in[2]), .Q (out[2]));
endmodule

module mexor4(in, out);
  input [5:0] in;
  output [5:0] out;
  wire [5:0] in;
  wire [5:0] out;
  wire n_1, n_2;
  assign out[0] = in[0];
  assign out[1] = in[1];
  NAND20 g800(.A (in[0]), .B (in[1]), .Q (n_1));
  INV2 g801(.A (n_1), .Q (n_2));
  XNR20 g805(.A (n_2), .B (in[5]), .Q (out[5]));
  XNR20 g802(.A (n_2), .B (in[4]), .Q (out[4]));
  XNR20 g803(.A (n_2), .B (in[3]), .Q (out[3]));
  XNR20 g804(.A (n_2), .B (in[2]), .Q (out[2]));
endmodule

module tcnot(in, out);
  input [3:0] in;
  output [3:0] out;
  wire [3:0] in;
  wire [3:0] out;
  assign out[0] = in[0];
  XNR20 g162(.A (in[0]), .B (in[1]), .Q (out[1]));
  XNR20 g163(.A (in[0]), .B (in[2]), .Q (out[2]));
  XNR20 g164(.A (in[0]), .B (in[3]), .Q (out[3]));
endmodule

module qcnot(in, out);
  input [4:0] in;
  output [4:0] out;
  wire [4:0] in;
  wire [4:0] out;
  assign out[0] = in[0];
  XNR20 g162(.A (in[0]), .B (in[1]), .Q (out[1]));
  XNR20 g163(.A (in[0]), .B (in[2]), .Q (out[2]));
  XNR20 g164(.A (in[0]), .B (in[3]), .Q (out[3]));
  XNR20 g165(.A (in[0]), .B (in[4]), .Q (out[4]));
endmodule

module tof(in, out);
  input [2:0] in;
  output [2:0] out;
  wire [2:0] in;
  wire [2:0] out;
  wire n_1, n_2;
  assign out[0] = in[0];
  assign out[1] = in[1];
  NAND20 g162(.A (in[0]), .B (in[1]), .Q (n_1));
  INV2 g163(.A (n_1), .Q (n_2));
  XNR20 g166(.A (n_2), .B (in[2]), .Q (out[2]));
endmodule

module DAFA(
    input [11:0] s_in,
    input [11:0] x_in,
    input [11:0] y_in,
    output [11:0] s_out,
    output [11:0] x_out,
    output [11:0] y_out,
    input ovf_in,
    output ovf_out
    );

// Block 1
wire [4:0] m1out;
mexor m1({s_in[4],s_in[3],s_in[0],y_in[2],x_in[2]},m1out);
/*
t3 x2 y2 s0
t3 x2 y2 s3
t3 x2 y2 s4*/

wire [3:0] m2out;
tcnot m2({y_in[2],y_in[1],y_in[0],x_in[2]},m2out);
/*
t2 x2 y0
t2 x2 y1
t2 x2 y2*/

wire [4:0] m3out;
mexor m3({m1out[4],m1out[3],m1out[2],s_in[2],m2out[3]},m3out);
/*
t3 y2 s2 s0
t3 y2 s2 s3
t3 y2 s2 s4*/

  wire [3:0] m4out;
tcnot m4({s_in[2],s_in[1],m3out[2],m2out[3]},m4out);
/*
t2 y2 s0
t2 y2 s1
t2 y2 s2*/

// Block 2
  wire [4:0] m5out;
mexor m5({s_in[5],m3out[3],m4out[2],y_in[4],x_in[4]},m5out);
/*
t3 x4 y4 s1
t3 x4 y4 s3
t3 x4 y4 s5*/

  wire [3:0] m6out;
tcnot m6({y_in[4],y_in[3],m2out[1],x_in[4]},m6out);
/*
t2 x4 y0
t2 x4 y3
t2 x4 y4*/

  wire[4:0] m7out;
mexor m7({m5out[4],m5out[3],m5out[2],y_in[4],m3out[4]},m7out);
/*
t3 s4 y4 s1
t3 s4 y4 s3
t3 s4 y4 s5*/

  wire [3:0] m8out;
tcnot m8({m3out[4],m7out[3],m4out[1],m6out[3]},m8out);
/*
t2 y4 s0
t2 y4 s3
t2 y4 s4*/

// Block 3

  wire [5:0] m9out;
mexor4 m9({s_in[6],m8out[2], m7out[2],m8out[1],y_in[5],x_in[5]},m9out);
/*
t3 x5 y5 s0
t3 x5 y5 s1
t3 x5 y5 s3
t3 x5 y5 s6*/

  wire [3:0] m10out;
tcnot m10({y_in[5],m6out[2],m2out[2],x_in[5] },m10out);
/*
t2 x5 y1
t2 x5 y3
t2 x5 y5*/

  wire [5:0] m11out;
mexor4 m11({m9out[5],m9out[4],m9out[3],m9out[2],m10out[3],m7out[4]},m11out);

/*
t3 s5 y5 s0
t3 s5 y5 s1
t3 s5 y5 s3 
t3 s5 y5 s6*/

  wire [3:0] m12out;
tcnot m12({m7out[4],m11out[4],m11out[3],m10out[3]},m12out);

/*
t2 y5 s1
t2 y5 s3
t2 y5 s5*/

// Block 4

  wire [4:0] m13out;
mexor m13({s_in[8],s_in[7],m11out[2],y_in[6],x_in[6]},m13out);
/*
t3 x6 y6 s0
t3 x6 y6 s7
t3 x6 y6 s8*/

  wire [4:0] m14out;
qcnot m14({y_in[6], m10out[2],m10out[1], m6out[1],x_in[6]},m14out);
/*
t2 x6 y0
t2 x6 y1
t2 x6 y3
t2 x6 y6*/

  wire [4:0] m15out;
mexor m15({m13out[4],m13out[3],m13out[2],m14out[4],m11out[5]},m15out);
/*
t3 s6 y6 s0
t3 s6 y6 s7
t3 s6 y6 s8 */

  wire [4:0] m16out;
qcnot m16({m11out[5],m12out[2],m12out[1],m15out[2],m14out[4]},m16out);
/*
t2 y6 s0
t2 y6 s1
t2 y6 s3
t2 y6 s6*/

// Block 5

  wire [4:0] m17out;
mexor m17({s_in[9],m15out[3],m16out[2],y_in[8],x_in[8]},m17out);
/*
t3 x8 y8 s1
t3 x8 y8 s7
t3 x8 y8 s9*/

  wire [3:0] m18out;
tcnot m18({y_in[8],y_in[7],m14out[1],x_in[8]},m18out);
/*
t2 x8 y0
t2 x8 y7
t2 x8 y8*/

  wire [4:0] m19out;
mexor m19({m17out[4],m17out[3],m17out[2],m18out[3],m15out[4]},m19out);
/*
t3 s8 y8 s1
t3 s8 y8 s7
t3 s8 y8 s9 */






  wire [3:0] m20out;
tcnot m20({m15out[4],m19out[3],m16out[1],m18out[3]},m20out);
/*
t2 y8 s0
t2 y8 s7
t2 y8 s8*/

// HERE

// Block 6

  wire [5:0] m21out;
mexor4 m21({s_in[10],m20out[2],m19out[2],m20out[1],y_in[9],x_in[9]},m21out);
/*
t3 x9 y9 s0
t3 x9 y9 s1
t3 x9 y9 s7
t3 x9 y9 s10*/

  wire [3:0] m22out;
tcnot m22({y_in[9],m18out[2],m14out[2],x_in[9]},m22out);
/*
t2 x9 y1
t2 x9 y7
t2 x9 y9*/

  wire [5:0] m23out;
mexor4 m23({m21out[5],m21out[4],m21out[3],m21out[2],m22out[3],m19out[4]},m23out);
/*
t3 s9 y9 s0
t3 s9 y9 s1
t3 s9 y9 s7 
t3 s9 y9 s10*/

  wire [3:0] m24out;
tcnot m24({m19out[4],m23out[4],m23out[3],m22out[3]},m24out);
/*
t2 y9 s1
t2 y9 s7
t2 y9 s9*/

// Block 7

  wire [4:0] m25out;
mexor m25({s_in[11],m24out[2],m16out[3],y_in[10],x_in[10]},m25out);
/*
t3 x10 y10 s3
t3 x10 y10 s7
t3 x10 y10 s11*/

  wire [4:0] m26out;
qcnot m26({y_in[10],m22out[2],m22out[1],m18out[1],x_in[10]},m26out);
/*
t2 x10 y0
t2 x10 y1
t2 x10 y7
t2 x10 y10*/

  wire [4:0] m27out;
mexor m27({m25out[4],m25out[3],m25out[2],m26out[4],m23out[5]},m27out);
/*
t3 s10 y10 s3
t3 s10 y10 s7
t3 s10 y10 s11*/

  wire [4:0] m28out;
qcnot m28({m23out[5],m27out[3],m24out[1],m23out[2],m26out[4]},m28out);
/*
t2 y10 s0
t2 y10 s1
t2 y10 s7
t2 y10 s10*/

// Block 8

  wire [2:0] m29out;
tof m29({ovf_in,y_in[11],x_in[11]},m29out);
/*
t3 x11 y11 ovf*/

  wire [3:0] m30out;
tcnot m30({y_in[11],m26out[3],m14out[3],x_in[11]},m30out);
/*
t2 x11 y3
t2 x11 y7
t2 x11 y11*/

  wire[2:0] m31out;
tof m31({m29out[2],m30out[3],m27out[4]},m31out);
/*
t3 s11 y11 ovf*/

  wire[3:0] m32out;
tcnot m32({m27out[4],m28out[3],m27out[2],m30out[3]},m32out);
/*
t2 y11 s3
t2 y11 s7
t2 y11 s11*/

assign ovf_out = m31out[2];
assign x_out = x_in;
assign y_out = {m30out[3],m26out[4],m22out[3],m18out[3],m30out[2],m14out[4],m10out[3],m6out[3],m30out[1],m2out[3],m26out[2],m26out[1]};
assign s_out = {m32out[3],m28out[4],m24out[3],m20out[3],m32out[2],m16out[4],m12out[3],m8out[3],m32out[1],m4out[3],m28out[2],m28out[1]};
endmodule

module register12bit_56(data_in, data_out, wr_e, clr, clk);
  input [11:0] data_in;
  input wr_e, clr, clk;
  output [11:0] data_out;
  wire [11:0] data_in;
  wire wr_e, clr, clk;
  wire [11:0] data_out;
  wire UNCONNECTED17, UNCONNECTED18, UNCONNECTED19, UNCONNECTED20,
       UNCONNECTED21, UNCONNECTED22, UNCONNECTED23, UNCONNECTED24;
  wire UNCONNECTED25, UNCONNECTED26, UNCONNECTED27, UNCONNECTED28, n_0;
  DFEC1 \data_out_reg[0] (.RN (n_0), .C (clk), .D (data_in[0]), .E
       (wr_e), .Q (data_out[0]), .QN (UNCONNECTED17));
  DFEC1 \data_out_reg[10] (.RN (n_0), .C (clk), .D (data_in[10]), .E
       (wr_e), .Q (data_out[10]), .QN (UNCONNECTED18));
  DFEC1 \data_out_reg[6] (.RN (n_0), .C (clk), .D (data_in[6]), .E
       (wr_e), .Q (data_out[6]), .QN (UNCONNECTED19));
  DFEC1 \data_out_reg[7] (.RN (n_0), .C (clk), .D (data_in[7]), .E
       (wr_e), .Q (data_out[7]), .QN (UNCONNECTED20));
  DFEC1 \data_out_reg[8] (.RN (n_0), .C (clk), .D (data_in[8]), .E
       (wr_e), .Q (data_out[8]), .QN (UNCONNECTED21));
  DFEC1 \data_out_reg[9] (.RN (n_0), .C (clk), .D (data_in[9]), .E
       (wr_e), .Q (data_out[9]), .QN (UNCONNECTED22));
  DFEC1 \data_out_reg[11] (.RN (n_0), .C (clk), .D (data_in[11]), .E
       (wr_e), .Q (data_out[11]), .QN (UNCONNECTED23));
  DFEC1 \data_out_reg[1] (.RN (n_0), .C (clk), .D (data_in[1]), .E
       (wr_e), .Q (data_out[1]), .QN (UNCONNECTED24));
  DFEC1 \data_out_reg[2] (.RN (n_0), .C (clk), .D (data_in[2]), .E
       (wr_e), .Q (data_out[2]), .QN (UNCONNECTED25));
  DFEC1 \data_out_reg[3] (.RN (n_0), .C (clk), .D (data_in[3]), .E
       (wr_e), .Q (data_out[3]), .QN (UNCONNECTED26));
  DFEC1 \data_out_reg[4] (.RN (n_0), .C (clk), .D (data_in[4]), .E
       (wr_e), .Q (data_out[4]), .QN (UNCONNECTED27));
  DFEC1 \data_out_reg[5] (.RN (n_0), .C (clk), .D (data_in[5]), .E
       (wr_e), .Q (data_out[5]), .QN (UNCONNECTED28));
  INV1 g65(.A (clr), .Q (n_0));
endmodule

module CU(INSTR, OVF, clk, reset, WEa, WEb, WEpc, CTRLa, CTRLpc,
     CTRLaddr, RW, CIN);
  input [2:0] INSTR;
  input OVF, clk, reset;
  output WEa, WEb, WEpc, CTRLa, CTRLpc, CTRLaddr, RW, CIN;
  wire [2:0] INSTR;
  wire OVF, clk, reset;
  wire WEa, WEb, WEpc, CTRLa, CTRLpc, CTRLaddr, RW, CIN;
  wire [3:0] state;
  wire UNCONNECTED29, UNCONNECTED30, UNCONNECTED31, UNCONNECTED32,
       UNCONNECTED33, UNCONNECTED34, UNCONNECTED35, UNCONNECTED36;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51;
  assign RW = 1'b0;
  DFC3 \state_reg[1] (.RN (n_6), .C (clk), .D (n_49), .Q (state[1]),
       .QN (n_1));
  DFC3 \state_reg[0] (.RN (n_6), .C (clk), .D (n_50), .Q (state[0]),
       .QN (n_2));
  DFE1 CIN_reg(.C (clk), .D (INSTR[0]), .E (n_44), .Q (CIN), .QN
       (UNCONNECTED29));
  DFP3 CTRLa_reg(.SN (n_6), .C (clk), .D (n_46), .Q (CTRLa), .QN
       (UNCONNECTED30));
  DFP3 WEpc_reg(.SN (n_6), .C (clk), .D (n_47), .Q (WEpc), .QN
       (UNCONNECTED31));
  DFC3 \state_reg[2] (.RN (n_6), .C (clk), .D (n_48), .Q (state[2]),
       .QN (UNCONNECTED32));
  NAND30 g2254(.A (n_42), .B (n_40), .C (n_34), .Q (n_50));
  OAI2110 g2255(.A (n_3), .B (n_34), .C (n_42), .D (n_20), .Q (n_49));
  DFC3 WEa_reg(.RN (n_6), .C (clk), .D (n_39), .Q (WEa), .QN
       (UNCONNECTED33));
  DFC3 \state_reg[3] (.RN (n_6), .C (clk), .D (n_37), .Q (n_51), .QN
       (n_0));
  DFC3 CTRLpc_reg(.RN (n_6), .C (clk), .D (n_41), .Q (CTRLpc), .QN
       (UNCONNECTED34));
  DFC3 WEb_reg(.RN (n_6), .C (clk), .D (n_43), .Q (WEb), .QN
       (UNCONNECTED35));
  OAI2110 g2260(.A (n_10), .B (n_30), .C (n_34), .D (n_22), .Q (n_48));
  NAND40 g2261(.A (n_26), .B (n_24), .C (n_28), .D (n_19), .Q (n_47));
  OAI210 g2262(.A (n_2), .B (n_19), .C (n_45), .Q (n_46));
  NAND20 g2263(.A (n_35), .B (CTRLa), .Q (n_45));
  NOR20 g2264(.A (reset), .B (n_35), .Q (n_44));
  NAND20 g2265(.A (n_32), .B (n_24), .Q (n_43));
  NAND30 g2266(.A (n_31), .B (n_3), .C (INSTR[1]), .Q (n_42));
  OAI310 g2267(.A (n_1), .B (n_2), .C (n_12), .D (n_33), .Q (n_41));
  AOI220 g2268(.A (n_29), .B (INSTR[0]), .C (n_51), .D (state[0]), .Q
       (n_40));
  CLKIN2 g2269(.A (n_38), .Q (n_39));
  AOI220 g2270(.A (n_31), .B (n_10), .C (n_15), .D (WEa), .Q (n_38));
  CLKIN2 g2271(.A (n_36), .Q (n_37));
  AOI220 g2272(.A (n_29), .B (INSTR[1]), .C (n_17), .D (n_51), .Q
       (n_36));
  DFC3 CTRLaddr_reg(.RN (n_6), .C (clk), .D (n_27), .Q (CTRLaddr), .QN
       (UNCONNECTED36));
  NAND20 g2274(.A (n_31), .B (n_4), .Q (n_35));
  NAND20 g2275(.A (n_29), .B (n_4), .Q (n_34));
  AOI220 g2276(.A (n_23), .B (OVF), .C (n_15), .D (CTRLpc), .Q (n_33));
  AOI220 g2277(.A (n_16), .B (n_21), .C (n_15), .D (WEb), .Q (n_32));
  CLKIN2 g2278(.A (n_31), .Q (n_30));
  NOR30 g2279(.A (n_17), .B (n_51), .C (INSTR[2]), .Q (n_31));
  NOR30 g2280(.A (n_17), .B (n_51), .C (n_5), .Q (n_29));
  AOI220 g2281(.A (n_14), .B (n_18), .C (n_0), .D (state[0]), .Q
       (n_28));
  OAI310 g2282(.A (state[0]), .B (n_1), .C (n_12), .D (n_25), .Q
       (n_27));
  AOI220 g2283(.A (n_15), .B (WEpc), .C (n_11), .D (n_1), .Q (n_26));
  NAND20 g2284(.A (n_15), .B (CTRLaddr), .Q (n_25));
  INV2 g2285(.A (n_23), .Q (n_24));
  NOR20 g2286(.A (n_0), .B (n_17), .Q (n_23));
  OAI210 g2287(.A (n_51), .B (n_7), .C (state[2]), .Q (n_22));
  OAI220 g2288(.A (n_8), .B (INSTR[0]), .C (n_10), .D (INSTR[2]), .Q
       (n_21));
  AOI220 g2289(.A (n_11), .B (n_7), .C (n_51), .D (state[1]), .Q
       (n_20));
  NAND20 g2290(.A (n_14), .B (state[1]), .Q (n_19));
  NAND20 g2291(.A (n_9), .B (INSTR[2]), .Q (n_18));
  CLKIN2 g2292(.A (n_17), .Q (n_16));
  NAND20 g2293(.A (n_13), .B (n_2), .Q (n_17));
  NOR20 g2294(.A (n_0), .B (n_13), .Q (n_15));
  NOR20 g2295(.A (state[2]), .B (n_51), .Q (n_14));
  NOR20 g2296(.A (state[2]), .B (state[1]), .Q (n_13));
  INV2 g2297(.A (n_12), .Q (n_11));
  NAND20 g2298(.A (n_0), .B (state[2]), .Q (n_12));
  INV1 g2299(.A (n_10), .Q (n_9));
  NAND20 g2300(.A (INSTR[0]), .B (INSTR[1]), .Q (n_10));
  NAND20 g2301(.A (n_4), .B (INSTR[2]), .Q (n_8));
  NOR20 g2302(.A (state[1]), .B (n_2), .Q (n_7));
  INV1 g2303(.A (reset), .Q (n_6));
  CLKIN2 g2305(.A (INSTR[2]), .Q (n_5));
  INV2 g2307(.A (INSTR[1]), .Q (n_4));
  INV2 g2308(.A (INSTR[0]), .Q (n_3));
endmodule

module register12bit_55(data_in, data_out, wr_e, clr, clk);
  input [11:0] data_in;
  input wr_e, clr, clk;
  output [11:0] data_out;
  wire [11:0] data_in;
  wire wr_e, clr, clk;
  wire [11:0] data_out;
  wire UNCONNECTED37, UNCONNECTED38, UNCONNECTED39, UNCONNECTED40,
       UNCONNECTED41, UNCONNECTED42, UNCONNECTED43, UNCONNECTED44;
  wire UNCONNECTED45, UNCONNECTED46, UNCONNECTED47, UNCONNECTED48, n_0;
  DFEC1 \data_out_reg[0] (.RN (n_0), .C (clk), .D (data_in[0]), .E
       (wr_e), .Q (data_out[0]), .QN (UNCONNECTED37));
  DFEC1 \data_out_reg[10] (.RN (n_0), .C (clk), .D (data_in[10]), .E
       (wr_e), .Q (data_out[10]), .QN (UNCONNECTED38));
  DFEC1 \data_out_reg[6] (.RN (n_0), .C (clk), .D (data_in[6]), .E
       (wr_e), .Q (data_out[6]), .QN (UNCONNECTED39));
  DFEC1 \data_out_reg[7] (.RN (n_0), .C (clk), .D (data_in[7]), .E
       (wr_e), .Q (data_out[7]), .QN (UNCONNECTED40));
  DFEC1 \data_out_reg[8] (.RN (n_0), .C (clk), .D (data_in[8]), .E
       (wr_e), .Q (data_out[8]), .QN (UNCONNECTED41));
  DFEC1 \data_out_reg[9] (.RN (n_0), .C (clk), .D (data_in[9]), .E
       (wr_e), .Q (data_out[9]), .QN (UNCONNECTED42));
  DFEC1 \data_out_reg[11] (.RN (n_0), .C (clk), .D (data_in[11]), .E
       (wr_e), .Q (data_out[11]), .QN (UNCONNECTED43));
  DFEC1 \data_out_reg[1] (.RN (n_0), .C (clk), .D (data_in[1]), .E
       (wr_e), .Q (data_out[1]), .QN (UNCONNECTED44));
  DFEC1 \data_out_reg[2] (.RN (n_0), .C (clk), .D (data_in[2]), .E
       (wr_e), .Q (data_out[2]), .QN (UNCONNECTED45));
  DFEC1 \data_out_reg[3] (.RN (n_0), .C (clk), .D (data_in[3]), .E
       (wr_e), .Q (data_out[3]), .QN (UNCONNECTED46));
  DFEC1 \data_out_reg[4] (.RN (n_0), .C (clk), .D (data_in[4]), .E
       (wr_e), .Q (data_out[4]), .QN (UNCONNECTED47));
  DFEC1 \data_out_reg[5] (.RN (n_0), .C (clk), .D (data_in[5]), .E
       (wr_e), .Q (data_out[5]), .QN (UNCONNECTED48));
  INV1 g65(.A (clr), .Q (n_0));
endmodule

module mexor4_41(in, out);
  input [5:0] in;
  output [5:0] out;
  wire [5:0] in;
  wire [5:0] out;
  wire n_2;
  assign out[0] = 1'b0;
  assign out[1] = 1'b0;
  IMUX20 g152(.A (out[5]), .B (n_2), .S (in[4]), .Q (out[4]));
  IMUX20 g153(.A (out[5]), .B (n_2), .S (in[3]), .Q (out[3]));
  IMUX20 g154(.A (out[5]), .B (n_2), .S (in[2]), .Q (out[2]));
  INV2 g155(.A (n_2), .Q (out[5]));
  NAND20 g156(.A (in[0]), .B (in[1]), .Q (n_2));
endmodule

module tcnot_63(in, out);
  input [3:0] in;
  output [3:0] out;
  wire [3:0] in;
  wire [3:0] out;
  assign out[0] = 1'b0;
  XNR20 g118(.A (in[3]), .B (in[0]), .Q (out[3]));
  XNR20 g119(.A (in[1]), .B (in[0]), .Q (out[1]));
  XNR20 g120(.A (in[2]), .B (in[0]), .Q (out[2]));
endmodule

module mexor_24(in, out);
  input [4:0] in;
  output [4:0] out;
  wire [4:0] in;
  wire [4:0] out;
  wire n_1;
  assign out[0] = 1'b0;
  assign out[1] = 1'b0;
  assign out[3] = 1'b0;
  IMUX20 g79(.A (out[4]), .B (n_1), .S (in[2]), .Q (out[2]));
  CLKIN3 g80(.A (n_1), .Q (out[4]));
  NAND20 g81(.A (in[0]), .B (in[1]), .Q (n_1));
endmodule

module qcnot_50(in, out);
  input [4:0] in;
  output [4:0] out;
  wire [4:0] in;
  wire [4:0] out;
  assign out[0] = 1'b0;
  XNR20 g157(.A (in[4]), .B (in[0]), .Q (out[4]));
  XNR20 g158(.A (in[2]), .B (in[0]), .Q (out[2]));
  XNR20 g159(.A (in[3]), .B (in[0]), .Q (out[3]));
  XNR20 g160(.A (in[1]), .B (in[0]), .Q (out[1]));
endmodule

module mexor_22(in, out);
  input [4:0] in;
  output [4:0] out;
  wire [4:0] in;
  wire [4:0] out;
  wire n_1, n_2;
  assign out[0] = 1'b0;
  assign out[1] = 1'b0;
  IMUX20 g104(.A (out[4]), .B (n_2), .S (in[2]), .Q (out[2]));
  NOR20 g105(.A (n_1), .B (out[4]), .Q (out[3]));
  CLKIN3 g106(.A (n_2), .Q (out[4]));
  NAND20 g107(.A (in[0]), .B (in[1]), .Q (n_2));
  CLKIN2 g108(.A (in[0]), .Q (n_1));
endmodule

module tcnot_61(in, out);
  input [3:0] in;
  output [3:0] out;
  wire [3:0] in;
  wire [3:0] out;
  assign out[0] = 1'b0;
  XNR20 g118(.A (in[3]), .B (in[0]), .Q (out[3]));
  XNR20 g119(.A (in[1]), .B (in[0]), .Q (out[1]));
  XNR20 g120(.A (in[2]), .B (in[0]), .Q (out[2]));
endmodule

module mexor4_39(in, out);
  input [5:0] in;
  output [5:0] out;
  wire [5:0] in;
  wire [5:0] out;
  wire n_2;
  assign out[0] = 1'b0;
  assign out[1] = 1'b0;
  IMUX20 g152(.A (out[5]), .B (n_2), .S (in[4]), .Q (out[4]));
  IMUX20 g153(.A (out[5]), .B (n_2), .S (in[3]), .Q (out[3]));
  IMUX20 g154(.A (out[5]), .B (n_2), .S (in[2]), .Q (out[2]));
  INV2 g155(.A (n_2), .Q (out[5]));
  NAND20 g156(.A (in[0]), .B (in[1]), .Q (n_2));
endmodule

module tcnot_59(in, out);
  input [3:0] in;
  output [3:0] out;
  wire [3:0] in;
  wire [3:0] out;
  assign out[0] = 1'b0;
  XNR20 g118(.A (in[3]), .B (in[0]), .Q (out[3]));
  XNR20 g119(.A (in[1]), .B (in[0]), .Q (out[1]));
  XNR20 g120(.A (in[2]), .B (in[0]), .Q (out[2]));
endmodule

module mexor_20(in, out);
  input [4:0] in;
  output [4:0] out;
  wire [4:0] in;
  wire [4:0] out;
  wire n_2;
  assign out[0] = 1'b0;
  assign out[1] = 1'b0;
  IMUX20 g110(.A (out[4]), .B (n_2), .S (in[3]), .Q (out[3]));
  IMUX20 g111(.A (out[4]), .B (n_2), .S (in[2]), .Q (out[2]));
  INV2 g112(.A (n_2), .Q (out[4]));
  NAND20 g113(.A (in[0]), .B (in[1]), .Q (n_2));
endmodule

module qcnot_48(in, out);
  input [4:0] in;
  output [4:0] out;
  wire [4:0] in;
  wire [4:0] out;
  assign out[0] = 1'b0;
  XNR20 g157(.A (in[4]), .B (in[0]), .Q (out[4]));
  XNR20 g158(.A (in[2]), .B (in[0]), .Q (out[2]));
  XNR20 g159(.A (in[3]), .B (in[0]), .Q (out[3]));
  XNR20 g160(.A (in[1]), .B (in[0]), .Q (out[1]));
endmodule

module tcnot_57(in, out);
  input [3:0] in;
  output [3:0] out;
  wire [3:0] in;
  wire [3:0] out;
  assign out[0] = 1'b0;
  XNR20 g118(.A (in[3]), .B (in[0]), .Q (out[3]));
  XNR20 g119(.A (in[1]), .B (in[0]), .Q (out[1]));
  XNR20 g120(.A (in[2]), .B (in[0]), .Q (out[2]));
endmodule

module mexor_26(in, out);
  input [4:0] in;
  output [4:0] out;
  wire [4:0] in;
  wire [4:0] out;
  wire n_1, n_3;
  assign out[0] = 1'b0;
  assign out[1] = 1'b0;
  assign out[2] = 1'b0;
  CLKIN3 g84(.A (n_3), .Q (out[4]));
  NAND20 g85(.A (in[1]), .B (in[0]), .Q (n_3));
  NOR20 g86(.A (in[1]), .B (n_1), .Q (out[3]));
  CLKIN2 g87(.A (in[0]), .Q (n_1));
endmodule

module tcnot_65(in, out);
  input [3:0] in;
  output [3:0] out;
  wire [3:0] in;
  wire [3:0] out;
  assign out[0] = 1'b0;
  assign out[1] = 1'b0;
  XNR20 g90(.A (in[0]), .B (in[3]), .Q (out[3]));
  XNR20 g91(.A (in[2]), .B (in[0]), .Q (out[2]));
endmodule

module DAFA_14(s_in, x_in, y_in, s_out, x_out, y_out, ovf_in, ovf_out);
  input [11:0] s_in, x_in, y_in;
  input ovf_in;
  output [11:0] s_out, x_out, y_out;
  output ovf_out;
  wire [11:0] s_in, x_in, y_in;
  wire ovf_in;
  wire [11:0] s_out, x_out, y_out;
  wire ovf_out;
  wire [4:0] m7out;
  wire [5:0] m11out;
  wire [3:0] m12out;
  wire [4:0] m15out;
  wire [4:0] m16out;
  wire [4:0] m19out;
  wire [3:0] m20out;
  wire [5:0] m23out;
  wire [3:0] m24out;
  wire [4:0] m27out;
  wire [4:0] m28out;
  wire [3:0] m32out;
  wire [3:0] m8out;
  wire UNCONNECTED49, UNCONNECTED50, UNCONNECTED51, n_0, n_1, n_2, n_3,
       n_4;
  wire n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_13, n_15;
  assign ovf_out = 1'b0;
  assign y_out[0] = 1'b0;
  assign y_out[1] = 1'b0;
  assign y_out[2] = 1'b0;
  assign y_out[3] = 1'b0;
  assign y_out[4] = 1'b0;
  assign y_out[5] = 1'b0;
  assign y_out[6] = 1'b0;
  assign y_out[7] = 1'b0;
  assign y_out[8] = 1'b0;
  assign y_out[9] = 1'b0;
  assign y_out[10] = 1'b0;
  assign y_out[11] = 1'b0;
  assign x_out[0] = 1'b0;
  assign x_out[1] = 1'b0;
  assign x_out[2] = 1'b0;
  assign x_out[3] = 1'b0;
  assign x_out[4] = 1'b0;
  assign x_out[5] = 1'b0;
  assign x_out[6] = 1'b0;
  assign x_out[7] = 1'b0;
  assign x_out[8] = 1'b0;
  assign x_out[9] = 1'b0;
  assign x_out[10] = 1'b0;
  assign x_out[11] = 1'b0;
  assign s_out[2] = 1'b0;
  mexor4_41 m11(.in ({1'b1, n_2, m7out[3], y_in[4], n_15, m7out[4]}),
       .out (m11out));
  tcnot_63 m12(.in ({m7out[4], m11out[4:3], n_15}), .out ({s_out[5],
       m12out[2:0]}));
  mexor_24 m15(.in ({2'b11, n_3, n_13, m11out[5]}), .out ({m15out[4],
       UNCONNECTED49, m15out[2:0]}));
  qcnot_50 m16(.in ({m11out[5], m12out[2:1], m15out[2], n_13}), .out
       ({s_out[6], m16out[3:0]}));
  mexor_22 m19(.in ({2'b10, n_5, n_12, m15out[4]}), .out (m19out));
  tcnot_61 m20(.in ({m15out[4], m19out[3], m16out[1], n_12}), .out
       ({s_out[8], m20out[2:0]}));
  mexor4_39 m23(.in ({1'b1, n_7, n_6, n_8, n_11, m19out[4]}), .out
       (m23out));
  tcnot_59 m24(.in ({m19out[4], m23out[4:3], n_11}), .out ({s_out[9],
       m24out[2:0]}));
  mexor_20 m27(.in ({1'b1, n_9, n_4, n_10, m23out[5]}), .out (m27out));
  qcnot_48 m28(.in ({m23out[5], m27out[3], m24out[1], m23out[2],
       n_10}), .out ({s_out[10], m28out[3], s_out[1:0], m28out[0]}));
  tcnot_57 m32(.in ({m27out[4], m28out[3], m27out[2], n_0}), .out
       ({s_out[11], s_out[7], s_out[3], m32out[0]}));
  mexor_26 m7(.in ({3'b100, y_in[4], y_in[2]}), .out ({m7out[4:3],
       UNCONNECTED50, m7out[1:0]}));
  tcnot_65 m8(.in ({y_in[2], m7out[3], 1'b1, n_1}), .out ({s_out[4],
       m8out[2], UNCONNECTED51, m8out[0]}));
  INV0 g66(.A (m24out[2]), .Q (n_9));
  INV0 g70(.A (m20out[1]), .Q (n_8));
  INV0 g69(.A (m20out[2]), .Q (n_7));
  INV0 g68(.A (m19out[2]), .Q (n_6));
  INV0 g72(.A (m16out[2]), .Q (n_5));
  INV0 g65(.A (m16out[3]), .Q (n_4));
  INV0 g75(.A (m11out[2]), .Q (n_3));
  INV0 g76(.A (m8out[2]), .Q (n_2));
  CLKIN2 g74(.A (y_in[6]), .Q (n_13));
  CLKIN1 g77(.A (y_in[5]), .Q (n_15));
  INV1 g78(.A (y_in[4]), .Q (n_1));
  CLKIN2 g67(.A (y_in[10]), .Q (n_10));
  CLKIN1 g73(.A (y_in[8]), .Q (n_12));
  CLKIN1 g64(.A (y_in[11]), .Q (n_0));
  CLKIN1 g71(.A (y_in[9]), .Q (n_11));
endmodule

module dff(data_in, data_out, wr_e, clr, clk);
  input data_in, wr_e, clr, clk;
  output data_out;
  wire data_in, wr_e, clr, clk;
  wire data_out;
  wire UNCONNECTED52;
  DFE1 data_out_reg(.C (clk), .D (data_in), .E (wr_e), .Q (data_out),
       .QN (UNCONNECTED52));
endmodule

module mux12bit(a, b, sel, x);
  input [11:0] a, b;
  input sel;
  output [11:0] x;
  wire [11:0] a, b;
  wire sel;
  wire [11:0] x;
  MUX21 g517(.A (a[11]), .B (b[11]), .S (sel), .Q (x[11]));
  MUX21 g518(.A (a[8]), .B (b[8]), .S (sel), .Q (x[8]));
  MUX21 g519(.A (a[5]), .B (b[5]), .S (sel), .Q (x[5]));
  MUX21 g520(.A (a[4]), .B (b[4]), .S (sel), .Q (x[4]));
  MUX21 g521(.A (a[7]), .B (b[7]), .S (sel), .Q (x[7]));
  MUX21 g522(.A (a[3]), .B (b[3]), .S (sel), .Q (x[3]));
  MUX21 g523(.A (a[2]), .B (b[2]), .S (sel), .Q (x[2]));
  MUX21 g524(.A (a[10]), .B (b[10]), .S (sel), .Q (x[10]));
  MUX21 g525(.A (a[9]), .B (b[9]), .S (sel), .Q (x[9]));
  MUX21 g526(.A (a[6]), .B (b[6]), .S (sel), .Q (x[6]));
  MUX21 g527(.A (a[1]), .B (b[1]), .S (sel), .Q (x[1]));
  MUX21 g528(.A (a[0]), .B (b[0]), .S (sel), .Q (x[0]));
endmodule

module mux12bit_47(a, b, sel, x);
  input [11:0] a, b;
  input sel;
  output [11:0] x;
  wire [11:0] a, b;
  wire sel;
  wire [11:0] x;
  MUX21 g517(.A (a[11]), .B (b[11]), .S (sel), .Q (x[11]));
  MUX21 g518(.A (a[8]), .B (b[8]), .S (sel), .Q (x[8]));
  MUX21 g519(.A (a[5]), .B (b[5]), .S (sel), .Q (x[5]));
  MUX21 g520(.A (a[4]), .B (b[4]), .S (sel), .Q (x[4]));
  MUX21 g521(.A (a[7]), .B (b[7]), .S (sel), .Q (x[7]));
  MUX21 g522(.A (a[3]), .B (b[3]), .S (sel), .Q (x[3]));
  MUX21 g523(.A (a[2]), .B (b[2]), .S (sel), .Q (x[2]));
  MUX21 g524(.A (a[10]), .B (b[10]), .S (sel), .Q (x[10]));
  MUX21 g525(.A (a[9]), .B (b[9]), .S (sel), .Q (x[9]));
  MUX21 g526(.A (a[6]), .B (b[6]), .S (sel), .Q (x[6]));
  MUX21 g527(.A (a[1]), .B (b[1]), .S (sel), .Q (x[1]));
  MUX21 g528(.A (a[0]), .B (b[0]), .S (sel), .Q (x[0]));
endmodule

module mux12bit_46(a, b, sel, x);
  input [11:0] a, b;
  input sel;
  output [11:0] x;
  wire [11:0] a, b;
  wire sel;
  wire [11:0] x;
  MUX21 g517(.A (a[11]), .B (b[11]), .S (sel), .Q (x[11]));
  MUX21 g518(.A (a[8]), .B (b[8]), .S (sel), .Q (x[8]));
  MUX21 g519(.A (a[5]), .B (b[5]), .S (sel), .Q (x[5]));
  MUX21 g520(.A (a[4]), .B (b[4]), .S (sel), .Q (x[4]));
  MUX21 g521(.A (a[7]), .B (b[7]), .S (sel), .Q (x[7]));
  MUX21 g522(.A (a[3]), .B (b[3]), .S (sel), .Q (x[3]));
  MUX21 g523(.A (a[2]), .B (b[2]), .S (sel), .Q (x[2]));
  MUX21 g524(.A (a[10]), .B (b[10]), .S (sel), .Q (x[10]));
  MUX21 g525(.A (a[9]), .B (b[9]), .S (sel), .Q (x[9]));
  MUX21 g526(.A (a[6]), .B (b[6]), .S (sel), .Q (x[6]));
  MUX21 g527(.A (a[1]), .B (b[1]), .S (sel), .Q (x[1]));
  MUX21 g528(.A (a[0]), .B (b[0]), .S (sel), .Q (x[0]));
endmodule

module mpc_verilog(CLK, DATA_IN, INSTR, RESET, ADDR_OUT, DATA_OUT, RW);
  input CLK, RESET;
  input [11:0] DATA_IN;
  input [2:0] INSTR;
  output [11:0] ADDR_OUT, DATA_OUT;
  output RW;
  wire CLK, RESET;
  wire [11:0] DATA_IN;
  wire [2:0] INSTR;
  wire [11:0] ADDR_OUT, DATA_OUT;
  wire RW;
  wire [11:0] XLXN_298;
  wire [11:0] XLXN_502;
  wire [11:0] XLXN_347;
  wire [11:0] XLXN_338;
  wire [11:0] XLXN_503;
  wire [11:0] XLXN_371;
  wire CIN, CTRL_A, CTRL_PC, OVF, UNCONNECTED53, UNCONNECTED54,
       UNCONNECTED55, UNCONNECTED56;
  wire UNCONNECTED57, UNCONNECTED58, UNCONNECTED59, UNCONNECTED60,
       UNCONNECTED61, UNCONNECTED62, UNCONNECTED63, UNCONNECTED64;
  wire UNCONNECTED65, UNCONNECTED66, UNCONNECTED67, UNCONNECTED68,
       UNCONNECTED69, UNCONNECTED70, UNCONNECTED71, UNCONNECTED72;
  wire UNCONNECTED73, UNCONNECTED74, UNCONNECTED75, UNCONNECTED76,
       UNCONNECTED77, UNCONNECTED78, UNCONNECTED79, UNCONNECTED80;
  wire UNCONNECTED81, UNCONNECTED82, UNCONNECTED83, UNCONNECTED84,
       UNCONNECTED85, UNCONNECTED86, UNCONNECTED87, UNCONNECTED88;
  wire UNCONNECTED89, UNCONNECTED90, UNCONNECTED91, UNCONNECTED92,
       UNCONNECTED93, UNCONNECTED94, UNCONNECTED95, UNCONNECTED96;
  wire UNCONNECTED97, UNCONNECTED98, UNCONNECTED99, UNCONNECTED100,
       UNCONNECTED101, UNCONNECTED102, UNCONNECTED103, WE_A;
  wire WE_B, WE_PC, XLXN_80, n_0;
  register12bit A(.data_in (XLXN_298), .data_out (DATA_OUT), .wr_e
       (WE_A), .clr (RESET), .clk (CLK));
  DAFA ALU(.s_in (12'b000000000000), .x_in ({XLXN_502[11:8], 1'b0,
       XLXN_502[6:4], 1'b0, XLXN_502[2], 2'b00}), .y_in
       ({DATA_OUT[11:8], 1'b0, DATA_OUT[6:4], 1'b0, DATA_OUT[2],
       2'b00}), .s_out (XLXN_347), .x_out ({UNCONNECTED64,
       UNCONNECTED63, UNCONNECTED62, UNCONNECTED61, UNCONNECTED60,
       UNCONNECTED59, UNCONNECTED58, UNCONNECTED57, UNCONNECTED56,
       UNCONNECTED55, UNCONNECTED54, UNCONNECTED53}), .y_out
       ({UNCONNECTED76, UNCONNECTED75, UNCONNECTED74, UNCONNECTED73,
       UNCONNECTED72, UNCONNECTED71, UNCONNECTED70, UNCONNECTED69,
       UNCONNECTED68, UNCONNECTED67, UNCONNECTED66, UNCONNECTED65}),
       .ovf_in (CIN), .ovf_out (XLXN_80));
  register12bit_56 B(.data_in (DATA_IN), .data_out (XLXN_502), .wr_e
       (WE_B), .clr (RESET), .clk (CLK));
  CU ControlUnit(.INSTR (INSTR), .OVF (OVF), .clk (CLK), .reset
       (RESET), .WEa (WE_A), .WEb (WE_B), .WEpc (WE_PC), .CTRLa
       (CTRL_A), .CTRLpc (CTRL_PC), .CTRLaddr (RW), .RW
       (UNCONNECTED77), .CIN (CIN));
  register12bit_55 PC(.data_in (XLXN_338), .data_out (XLXN_503), .wr_e
       (WE_PC), .clr (RESET), .clk (CLK));
  DAFA_14 PC_INC(.s_in (12'b000000000000), .x_in (12'b000000000111),
       .y_in ({XLXN_503[11:8], 1'b0, XLXN_503[6:4], 1'b0, XLXN_503[2],
       2'b00}), .s_out ({XLXN_371[11:3], UNCONNECTED78,
       XLXN_371[1:0]}), .x_out ({UNCONNECTED90, UNCONNECTED89,
       UNCONNECTED88, UNCONNECTED87, UNCONNECTED86, UNCONNECTED85,
       UNCONNECTED84, UNCONNECTED83, UNCONNECTED82, UNCONNECTED81,
       UNCONNECTED80, UNCONNECTED79}), .y_out ({UNCONNECTED102,
       UNCONNECTED101, UNCONNECTED100, UNCONNECTED99, UNCONNECTED98,
       UNCONNECTED97, UNCONNECTED96, UNCONNECTED95, UNCONNECTED94,
       UNCONNECTED93, UNCONNECTED92, UNCONNECTED91}), .ovf_in (1'b0),
       .ovf_out (UNCONNECTED103));
  dff XLXI_106(.data_in (XLXN_80), .data_out (OVF), .wr_e (WE_A), .clr
       (1'b0), .clk (CLK));
  mux12bit XLXI_54(.a (XLXN_347), .b (DATA_IN), .sel (CTRL_A), .x
       (XLXN_298));
  mux12bit_47 XLXI_61(.a ({XLXN_371[11:3], n_0, XLXN_371[1:0]}), .b
       (DATA_IN), .sel (CTRL_PC), .x (XLXN_338));
  mux12bit_46 XLXI_65(.a (XLXN_503), .b (XLXN_502), .sel (RW), .x
       (ADDR_OUT));
  INV0 g4(.A (XLXN_503[2]), .Q (n_0));
endmodule
